/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/Astronaut.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Astronaut.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Astronaut_mesh.geometry} material={materials.Astronaut_mat} />
    </group>
  )
}

useGLTF.preload('/Astronaut.glb')
