/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/planet.glb 
*/

import React, {  useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/planet.glb')


  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-0.003, 0.024, -6.331]} rotation={[0.238, -0.545, 0.562]} scale={7}>
          <mesh geometry={nodes.planet002.geometry} material={materials['scene.001']} />
          <mesh geometry={nodes.planet003.geometry} material={materials['scene.001']} />
        </group>
      </group>
      <mesh geometry={nodes.Astronaut_mesh.geometry} material={materials.Astronaut_mat} position={[-2.326, -0.554, -2.342]} rotation={[Math.PI, -0.801, Math.PI]} />
      <group position={[-0.12, 0.05, 2.114]} scale={[0.006, 0.006, 0.009]}>
        <mesh geometry={nodes.ChamferBox017_1.geometry} material={materials['03___Default']} />
        <mesh geometry={nodes.ChamferBox017_1_1.geometry} material={materials['05___Default']} />
        <mesh geometry={nodes.ChamferBox017_1_2.geometry} material={materials['01___Default']} />
        <mesh geometry={nodes.ChamferBox017_1_3.geometry} material={materials['04___Default']} />
      </group>
    </group>
  )
}

useGLTF.preload('/planet.glb')
