/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/subfinal.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/subfinal.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-0.003, 0.024, -6.331]} rotation={[0.238, -0.545, 0.562]} scale={7}>
          <mesh geometry={nodes.planet002.geometry} material={materials['scene.001']} />
          <mesh geometry={nodes.planet003.geometry} material={materials['scene.001']} />
        </group>
      </group>
      <mesh geometry={nodes.Astronaut_mesh.geometry} material={materials.Astronaut_mat} position={[-2.326, -0.554, -2.342]} rotation={[Math.PI, -0.801, Math.PI]} />
      <mesh geometry={nodes.group1631870305.geometry} material={materials.mat21} position={[-0.561, 0.144, 2.755]} rotation={[-Math.PI, 0.288, -Math.PI]} scale={2.422} />
      <mesh geometry={nodes.group2131501692.geometry} material={materials.mat17} position={[-0.561, 0.144, 2.755]} rotation={[-Math.PI, 0.288, -Math.PI]} scale={2.422} />
      <mesh geometry={nodes.group2115554823.geometry} material={materials.mat15} position={[-0.561, 0.144, 2.755]} rotation={[-Math.PI, 0.288, -Math.PI]} scale={2.422} />
      <mesh geometry={nodes.group861517382.geometry} material={materials.mat15} position={[-0.561, 0.144, 2.755]} rotation={[-Math.PI, 0.288, -Math.PI]} scale={2.422} />
      <mesh geometry={nodes.group1262710399.geometry} material={materials.mat17} position={[-0.561, 0.144, 2.755]} rotation={[-Math.PI, 0.288, -Math.PI]} scale={2.422} />
      <mesh geometry={nodes.group721205586.geometry} material={materials.mat22} position={[-0.561, 0.144, 2.755]} rotation={[-Math.PI, 0.288, -Math.PI]} scale={2.422} />
      <mesh geometry={nodes.group35764393.geometry} material={materials.mat22} position={[-0.561, 0.144, 2.755]} rotation={[-Math.PI, 0.288, -Math.PI]} scale={2.422} />
      <mesh geometry={nodes.group524729728.geometry} material={materials.mat9} position={[-0.561, 0.144, 2.755]} rotation={[-Math.PI, 0.288, -Math.PI]} scale={2.422} />
      <mesh geometry={nodes.group1639888595.geometry} material={materials.mat21} position={[-0.561, 0.144, 2.755]} rotation={[-Math.PI, 0.288, -Math.PI]} scale={2.422} />
      <mesh geometry={nodes.group1982090435.geometry} material={materials.mat22} position={[-0.561, 0.144, 2.755]} rotation={[-Math.PI, 0.288, -Math.PI]} scale={2.422} />
      <mesh geometry={nodes.group1164002630.geometry} material={materials.mat22} position={[-0.561, 0.144, 2.755]} rotation={[-Math.PI, 0.288, -Math.PI]} scale={2.422} />
      <mesh geometry={nodes.group1127867106.geometry} material={materials.mat22} position={[-0.561, 0.144, 2.755]} rotation={[-Math.PI, 0.288, -Math.PI]} scale={2.422} />
      <mesh geometry={nodes.group944565295.geometry} material={materials.mat22} position={[-0.561, 0.144, 2.755]} rotation={[-Math.PI, 0.288, -Math.PI]} scale={2.422} />
      <mesh geometry={nodes.group1420559667.geometry} material={materials.mat22} position={[-0.561, 0.144, 2.755]} rotation={[-Math.PI, 0.288, -Math.PI]} scale={2.422} />
      <mesh geometry={nodes.group646619783.geometry} material={materials.mat22} position={[-0.561, 0.144, 2.755]} rotation={[-Math.PI, 0.288, -Math.PI]} scale={2.422} />
      <mesh geometry={nodes.group2085192078.geometry} material={materials.mat22} position={[-0.561, 0.144, 2.755]} rotation={[-Math.PI, 0.288, -Math.PI]} scale={2.422} />
      <mesh geometry={nodes.group1506597832.geometry} material={materials.mat22} position={[-0.561, 0.144, 2.755]} rotation={[-Math.PI, 0.288, -Math.PI]} scale={2.422} />
      <mesh geometry={nodes.group1412601270.geometry} material={materials.mat22} position={[-0.561, 0.144, 2.755]} rotation={[-Math.PI, 0.288, -Math.PI]} scale={2.422} />
      <mesh geometry={nodes.group2130073709.geometry} material={materials.mat22} position={[-0.561, 0.144, 2.755]} rotation={[-Math.PI, 0.288, -Math.PI]} scale={2.422} />
      <mesh geometry={nodes.group1215636041.geometry} material={materials.mat22} position={[-0.561, 0.144, 2.755]} rotation={[-Math.PI, 0.288, -Math.PI]} scale={2.422} />
      <mesh geometry={nodes.group354029567.geometry} material={materials.mat22} position={[-0.561, 0.144, 2.755]} rotation={[-Math.PI, 0.288, -Math.PI]} scale={2.422} />
      <mesh geometry={nodes.group541733156.geometry} material={materials.mat22} position={[-0.561, 0.144, 2.755]} rotation={[-Math.PI, 0.288, -Math.PI]} scale={2.422} />
      <mesh geometry={nodes.group188804331.geometry} material={materials.mat22} position={[-0.561, 0.144, 2.755]} rotation={[-Math.PI, 0.288, -Math.PI]} scale={2.422} />
      <mesh geometry={nodes.group24878451.geometry} material={materials.mat22} position={[-0.561, 0.144, 2.755]} rotation={[-Math.PI, 0.288, -Math.PI]} scale={2.422} />
      <mesh geometry={nodes.group618472546.geometry} material={materials.mat22} position={[-0.561, 0.144, 2.755]} rotation={[-Math.PI, 0.288, -Math.PI]} scale={2.422} />
      <mesh geometry={nodes.group2031044348.geometry} material={materials.mat22} position={[-0.561, 0.144, 2.755]} rotation={[-Math.PI, 0.288, -Math.PI]} scale={2.422} />
      <mesh geometry={nodes.group1344882062.geometry} material={materials.mat22} position={[-0.561, 0.144, 2.755]} rotation={[-Math.PI, 0.288, -Math.PI]} scale={2.422} />
      <mesh geometry={nodes.group51422144.geometry} material={materials.mat22} position={[-0.561, 0.144, 2.755]} rotation={[-Math.PI, 0.288, -Math.PI]} scale={2.422} />
      <mesh geometry={nodes.group627458418.geometry} material={materials.mat22} position={[-0.561, 0.144, 2.755]} rotation={[-Math.PI, 0.288, -Math.PI]} scale={2.422} />
      <mesh geometry={nodes.group1312281953.geometry} material={materials.mat22} position={[-0.561, 0.144, 2.755]} rotation={[-Math.PI, 0.288, -Math.PI]} scale={2.422} />
      <mesh geometry={nodes.group1139380957.geometry} material={materials.mat22} position={[-0.561, 0.144, 2.755]} rotation={[-Math.PI, 0.288, -Math.PI]} scale={2.422} />
      <mesh geometry={nodes.group806411317.geometry} material={materials.mat22} position={[-0.561, 0.144, 2.755]} rotation={[-Math.PI, 0.288, -Math.PI]} scale={2.422} />
      <mesh geometry={nodes.group396267525.geometry} material={materials.mat22} position={[-0.561, 0.144, 2.755]} rotation={[-Math.PI, 0.288, -Math.PI]} scale={2.422} />
      <mesh geometry={nodes.group1625508101.geometry} material={materials.mat22} position={[-0.561, 0.144, 2.755]} rotation={[-Math.PI, 0.288, -Math.PI]} scale={2.422} />
    </group>
  )
}

useGLTF.preload('/subfinal.glb')
